version: '3.4'
services:
  kohsaar.api:
    volumes:
      - 'c:/${ATTACH_DISK}/Kohsaar.Api/wwwroot:/usr/app/wwwroot/'
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Sandbox'
      - 'ConnectionString=server=db;port=3306;database=kohsaardb;userid=sa;password=${DB_PASSWORD};'
    build: 
      context: ../../Kohsaar.Api.Api/Kohsaars
      dockerfile: ./Dockerfile.original