version: '3.4'
services:
  kohsaar.api:
    image: 'abdullahgb/eshop.api:latest'
    container_name: kohsaar_api
    ports:
      - '5001:5000'
    restart: always
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: devops_default
