version: '3.4'
services:
  kohsaar.api:
    volumes:
      - 'c:/${ATTACH_DISK}/kohsaar/wwwroot:/usr/app/wwwroot/'
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Sandbox'
    build: 
      context: ../Kohsaar.Api
      dockerfile: ./Kohsaar/Dockerfile.original